export default `# Privacy Policy
Last updated: August 1, 2026
Organova operates this store and website, including all related information, content, features, tools, products and services, in order to provide you, the customer, with a curated shopping experience (the "Services"). This Privacy Policy describes how we collect, use, and disclose your personal information when you visit, use, or make a purchase or other transaction using the Services or otherwise communicate with us. If there is a conflict between our Terms of Service and this Privacy Policy, this Privacy Policy controls with respect to the collection, processing, and disclosure of your personal information.
Please read this Privacy Policy carefully. By using and accessing any of the Services, you acknowledge that you have read this Privacy Policy and understand the collection, use, and disclosure of your information as described in this Privacy Policy.
## Personal Information We Collect or Process
When we use the term "personal information," we are referring to information that identifies or can reasonably be linked to you or another person. Personal information does not include information that is collected anonymously or that has been de-identified, so that it cannot identify or be reasonably linked to you. We may collect or process the following categories of personal information, depending on how you interact with the Services, where you live, and as permitted or required by applicable law:
- **Contact details** including your name, shipping address, phone number, and email address.
- **Payment information** including transaction details, form of payment and payment confirmation. Card and PayPal account details are handled by PayPal and are not stored by us.
- **Transaction information** including the items you put in your basket or purchase, return or cancel, and your past transactions.
- **Communications with us** including the information you include in communications with us, for example, when sending a customer support inquiry.
- **Device information** including information about your device, browser, or network connection, your IP address, and other unique identifiers.
- **Usage information** including information regarding your interaction with the Services, including how and when you interact with or navigate the Services.
## Personal Information Sources
We may collect personal information from the following sources:
- **Directly from you** including when you visit or use the Services, place an order, communicate with us, or otherwise provide us with your personal information;
- **Automatically through the Services** including from your device when you use our products or services or visit our websites, and through the use of cookies and similar technologies;
- **From our service providers** including when we engage them to enable certain technology and when they collect or process your personal information on our behalf;
- **From our partners or other third parties.**
## How We Use Your Personal Information
Depending on how you interact with us or which of the Services you use, we may use personal information for the following purposes:
- **Provide, Tailor, and Improve the Services.** We use your personal information to provide you with the Services, including to perform our contract with you, to process your payments, to fulfill your orders, to remember your preferences and items you are interested in, to process purchases, returns, exchanges or other transactions, to arrange for shipping, and to facilitate any returns and exchanges. This may include using your personal information to better tailor and improve the Services.
- **Marketing and Advertising.** We may use your personal information for marketing and promotional purposes, such as to send marketing, advertising and promotional communications by email, text message or postal mail, where permitted by law.
- **Security and Fraud Prevention.** We use your personal information to provide a secure payment and shopping experience, detect, investigate or take action regarding possible fraudulent, illegal, unsafe, or malicious activity, protect public safety, and to secure our services.
- **Communicating with You.** We use your personal information to provide you with customer support, to be responsive to you, to provide effective services to you and to maintain our business relationship with you.
- **Legal Reasons.** We use your personal information to comply with applicable law or respond to valid legal process, including requests from law enforcement or government agencies, to investigate or participate in civil discovery, potential or actual litigation, or other adversarial legal proceedings, and to enforce or investigate potential violations of our terms or policies.
## How We Disclose Personal Information
In certain circumstances, we may disclose your personal information to third parties for legitimate purposes subject to this Privacy Policy. Such circumstances may include:
- With vendors and other third parties who perform services on our behalf (e.g. website hosting, payment processing, data analytics, customer support, cloud storage, fulfillment and shipping).
- With business and marketing partners to provide marketing services and advertise to you. Our business and marketing partners will use your information in accordance with their own privacy notices. Depending on where you reside, you may have a right to direct us not to share information about you to show you targeted advertisements and marketing based on your online activity.
- When you direct, request us or otherwise consent to our disclosure of certain information to third parties, such as to ship you products or through your use of social media widgets or login integrations.
- With our affiliates or otherwise within our corporate group.
- In connection with a business transaction such as a merger or bankruptcy, to comply with any applicable legal obligations (including to respond to subpoenas, search warrants and similar requests), to enforce any applicable terms of service or policies, and to protect or defend the Services, our rights, and the rights of our users or others.
## Our Service Providers
This website is hosted by Cloudflare, which processes information about your access to and use of the Services in order to deliver the website to you. Payments are processed by PayPal, which is responsible for the processing of your payment details under its own privacy notice. Information you submit to the Services may be transmitted to and shared with these providers, which may be located in countries other than where you reside, in order to provide the Services to you.
## Third Party Websites and Links
The Services may provide links to websites or other online platforms operated by third parties. If you follow links to sites not affiliated or controlled by us, you should review their privacy and security policies and other terms and conditions. We do not guarantee and are not responsible for the privacy or security of such sites, including the accuracy, completeness, or reliability of information found on these sites. Information you provide on public or semi-public venues, including information you share on third-party social networking platforms may also be viewable by other users of the Services and/or users of those third-party platforms without limitation as to its use by us or by a third party. Our inclusion of such links does not, by itself, imply any endorsement of the content on such platforms or of their owners or operators, except as disclosed on the Services.
## Children's Data
The Services are not intended to be used by children, and we do not knowingly collect any personal information about children under the age of majority in your jurisdiction. If you are the parent or guardian of a child who has provided us with their personal information, you may contact us using the contact details set out below to request that it be deleted.
## Security and Retention of Your Information
Please be aware that no security measures are perfect or impenetrable, and we cannot guarantee "perfect security." In addition, any information you send to us may not be secure while in transit. We recommend that you do not use unsecure channels to communicate sensitive or confidential information to us.
How long we retain your personal information depends on different factors, such as whether we need the information to provide you with Services, comply with legal obligations, resolve disputes or enforce other applicable contracts and policies.
## Your Rights and Choices
Depending on where you live, you may have some or all of the rights listed below in relation to your personal information. However, these rights are not absolute, may apply only in certain circumstances and, in certain cases, we may decline your request as permitted by law.
- **Right to Access / Know.** You may have a right to request access to personal information that we hold about you.
- **Right to Delete.** You may have a right to request that we delete personal information we maintain about you.
- **Right to Correct.** You may have a right to request that we correct inaccurate personal information we maintain about you.
- **Right of Portability.** You may have a right to receive a copy of the personal information we hold about you and to request that we transfer it to a third party, in certain circumstances and with certain exceptions.
- **Managing Communication Preferences.** We may send you promotional emails, and you may opt out of receiving these at any time by using the unsubscribe option displayed in our emails to you. If you opt out, we may still send you non-promotional emails, such as those about your orders that you have made.
**If you reside in the UK or European Economic Area,** and subject to exceptions and limitations provided by local law, you may exercise the following rights in addition to the rights outlined above:
- **Objection to Processing and Restriction of Processing:** You may have the right to ask us to stop or restrict our processing of personal information for certain purposes.
- **Withdrawal of Consent:** Where we rely on consent to process your personal information, you have the right to withdraw this consent. If you withdraw your consent, this will not affect the lawfulness of any processing based on your consent before its withdrawal.
You may exercise any of these rights by contacting us using the contact details provided below.
We will not discriminate against you for exercising any of these rights. We may need to verify your identity before we can process your requests, as permitted or required under applicable law. In accordance with applicable laws, you may designate an authorized agent to make requests on your behalf to exercise your rights. Before accepting such a request from an agent, we will require that the agent provide proof you have authorized them to act on your behalf, and we may need you to verify your identity directly with us. We will respond to your request in a timely manner as required under applicable law.
## Complaints
If you have complaints about how we process your personal information, please contact us using the contact details provided below. Depending on where you live, you may have the right to appeal our decision by contacting us using the contact details set out below, or lodge your complaint with your local data protection authority.
## International Transfers
Please note that we may transfer, store and process your personal information outside the country you live in.
If we transfer your personal information out of the European Economic Area or the United Kingdom, we will rely on recognized transfer mechanisms like the European Commission's Standard Contractual Clauses, or any equivalent contracts issued by the relevant competent authority of the UK, as relevant, unless the data transfer is to a country that has been determined to provide an adequate level of protection.
## Changes to This Privacy Policy
We may update this Privacy Policy from time to time, including to reflect changes to our practices or for other operational, legal, or regulatory reasons. We will post the revised Privacy Policy on this website, update the "Last updated" date and provide notice as required by applicable law.
## Contact
Should you have any questions about our privacy practices or this Privacy Policy, or if you would like to exercise any of the rights available to you, please call +44 7405 887737 or email us at <contact@organova.co.uk> or contact us at Dragonfly Heights, 3 Teal Road, Ilford IG3 8FY, United Kingdom. For the purpose of applicable data protection laws, we are the data controller of your personal information.
`;
